### ISSUE TITLE
Function not found : CBaseUser::PostCallbackToUI(int,uchar *,int)

### ISSUE THREAD

**Issue by xPaw** [m4dEngi/steamworks_dumper#2]
Seems like it broke at some point, this is latest beta.

@m4dEngi Could you take a look please? :)

**Comment by m4dEngi** [comment]
That explains a lot lol

**Comment by m4dEngi** [comment]
Oh. They finally stripped symtab.

**Comment by xPaw** [comment]
Are you willing to look into making this work again?

**Comment by m4dEngi** [comment]
Yes, but the information we can extract is now quite limited. (we can no longer extract full function prototypes with all those fancy correct type names for example).

**Comment by m4dEngi** [comment]
Sorry for long wait. Give new version a try.

**Comment by xPaw** [comment]
I got it compiled and updated tracker to download linux binaries.

> Loading module image... Done
Parsing image... Done
Found 422 callbacks
Found 34 enums

**Comment by m4dEngi** [comment]
> I got it compiled and updated tracker to download linux binaries.
> 
> There's code to dump interfaces, but unsure if it's supposed to work (if so, would be good to have a log line that it failed)
Probably SendSerializedFunction signature changed in beta... yeah, some verbose logging could be useful.
 
> P.S. wanna join steamdb discord?
Sure why not.

**Comment by xPaw** [comment]
>Probably SendSerializedFunction signature changed in beta... 

This will get annoying to keep track of haha

discord: https://steamdb.info/discord/
