### ISSUE TITLE
Handling IClientEngine

### ISSUE THREAD

**Issue by Rosentti** [m4dEngi/steamworks_dumper#3]
This doesn't seem to dump info about IClientEngine. This would be extremely useful info to have. Is it possible to get info about ClientEngine?

**Comment by m4dEngi** [comment]
> This would be extremely useful info to have.

Tell me more about it... 

IClientEngine is not trivial interface to dump and require manual analysis and recovery.

**Comment by 20PercentRendered** [comment]
Where could I start finding the functions or even how many functions there are? Currently have a function called `CSteamClient::CreateSteamPipeInternal` open in Ghidra (`ubuntu12_32/steamclient.so`), but it seems to only have NetworkingUtils construction happening in it. Is there a convenient function somewhere that has all initialization logic for ClientEngine or is it scattered about?

**Comment by 20PercentRendered** [comment]
Actually just found out you seem to have forked opensteamworks and updated IClientEngine.h. Will test tomorrow and see if it works well enough for my purposes (Steam GUI with Qt). Maybe this should be kept open if others have this same question.

**Comment by 20PercentRendered** [comment]
It seems as though it _could_ be possible to atleast partially dump IClientEngine (it's interfaces).
In steamui.so, there's a function called ClientAPI_Init, which has a bunch of asserts that tell you what interface it was trying to load:
![image](https://github.com/m4dEngi/steamworks_dumper/assets/32398752/03bada81-3941-4039-a7e2-5bc30e562588)
With these, it should be possible to atleast find the interface positions. It would require the user to also pass in steamui.so.

**Comment by m4dEngi** [comment]
This looks way easier to automate compared to what we got in steamclient library with its optimization and simd all over the place. 

I'll try to implement that.

**Comment by m4dEngi** [comment]
Added crude parser for `ClientAPI_Init()`  https://github.com/m4dEngi/steamworks_dumper/commit/9c76072d7d30d67f1710b7f2af14a3fe304c1954

**Comment by m4dEngi** [comment]
Unfortunately, these dumps are too imprecise about the number of function arguments to be used directly as a basis for code generation.
